apiVersion: v2
name: zenyard
description: Local Kubernetes stack for the Zenyard DevOps Challenge
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 18.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kube-prometheus-stack
    version: 86.2.3
    repository: https://prometheus-community.github.io/helm-charts
    condition: observability.metrics.enabled
  - name: loki-stack
    version: 2.10.3
    repository: https://grafana.github.io/helm-charts
    condition: observability.logs.enabled
