---
- name: Check if Helm is already installed
  stat:
    path: "{{ helm_bin }}"
  register: helm_bin_stat

- name: Install Helm
  shell: |
    curl -fsSL {{ helm_install_script_url }} | DESIRED_VERSION={{ helm_version }} bash
  become: true
  when: not helm_bin_stat.stat.exists

- name: Verify Helm version
  command: helm version --short
  changed_when: false
  register: helm_ver

- name: Show Helm version
  debug:
    msg: "Helm installed: {{ helm_ver.stdout }}"
