---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zenyard-postgresql
  namespace: zenyard
spec:
  encryptedData:
    password: AgBFexY/HFUsxMVz0hLh3HeEBDq1iVAetmxLMe5ng0om00XiEjwBC/4qAEH+IlPRwRWp1Ef5FRbhAigOjWD6c9CVWfeGPOp1MIN39xqS/xplK1kTUK/O+9Xm2RFEMhJTTzD/VyznTzGA0FgHN+gcn7wY20foat3qF3uZptFYCI1j+qKalkYOwBeraFdVFMU9d1CHMsiits/j8ozURY5WaC9ONfaN9tAq8J7DkpGANVndBkW7gH5Rqjdhvav7unzRf/g4Vktr4cnAhAjqnDIOrSfkUGCQIAY1pXDPTzafaM+rqSzNRYv/df3uYimYlM3cni3I8Ad9EHohW4Y/G6PbB4apPQbj6ONS0NpPjnvPnuilNJsEzVa6w4800sxXiFukvNjzX3SY45VNiiDXU8L1/3LYorBrzMePlfiuwwFm8I6xM+0Iq+OxVeku0cOtNz/N2OloBurHT6ZzR/61q80xZXN/KujBT4vh3vv7Xd4DaZEODiALFv4LxhR5KEOhldJ02vzHKg03OH2//farxJHHTjCLzphoTTWiPBRpAzyNJM36nnEuLV1OYiQpEBCKn3u/BYkBofxSGW3bI86joMxGsXG6X311GT2UVWvFV8YXYOjNwN2nqeo9xsaa6uWOD/BoYFX0+l0CBn41Gdfl06krvHMUMFtTqPsL537AGOhCZs0OjoNAIem4AvKpTfx7IEwwi+K+Rb+zxjG4+G7iva+m3xpNst2WLwhNyr4=
    postgres-password: AgAZiz7a72tqIoLIiis6/IjuEASLCxTtt2uwRnWMyV1dIvmIId+ZDCTfZoRSv59Xrz9vR4No9ZcomghBb8M4D9oBSd5ogpFy25Q0zQWCRvbbwiU6t05HUNI03WJx7HOZMUtb54sXNn8NRaOafNkeFCjutryFndin+lwCm295KhLSDrv0NckQCov1ROBoRVVUg6giGIhI8cu2xpUp1kaY6P1c7b+DoVSlvXoeYLSNlaQ5V0h84ukK5sK4a3YEKZQDSnbK+3DP/TNiySMnZOnocf2Q0h8L5/PsdikW6aYDWOWeUDFChFDupuXl6DZzulx2Go9sHhHJdWIcv24CZc6k2ry1aFBsjnGbCI1hOvJy6Sag9hyKLuLaIBHDRxh5GoWsJoY/kDn0x8ifRcviMewcycPiqA7IRLvf7t1+2BwiDKJYX88iLAGvmPnZ4ZVv6QVfKbW8PABYOLyruGj/r92k95+fBlc375zaitpmg9F7Us3tlACPN62O+btVAMOLH96f9TFcEFWiLRBDWzJLceY+JKirCZdue2aF3wMh520DLLmg77LQZQAVykpuL2ULjOxOHompPciR3hzstNKkapMLZVA4Fvemn3LImwgHnOaLqst54ATnzKvmdgsCHGXaZv4YmpdTxqp/y6Kf7VQb4l2+z195I7NT+TPbg6Gkgr1/2wjlwlam6MncnaabRsRiv8E71S6c0MZgNZN8k5WQM9lyjn4GZWeVljjaGfk=
  template:
    metadata:
      creationTimestamp: null
      name: zenyard-postgresql
      namespace: zenyard
