---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zenyard-grafana
  namespace: zenyard
spec:
  encryptedData:
    admin-password: AgAApXBm0mOrJH0XrzsD4NufmPunAT0CU+828atPpZxWWR4O528ftc/LZK7Ro+Oo/K+d9GDj4MexzaNPGj9ceAqIZFMPpTo6Skm5WueJ6w/sHeUpMyEl2cpOfJxi17kxBnzf545Xp1H9WpVUmmLaOYwwAXhKpRxKEFCsGI2BsZuXbenOdjfBRKuhX62pOE24k7MCbZ+7+mgH48T8buzRWNTMWr1/FV2ZYdBxjhf8pnMPT7+QrXn083oExDd0G31pJZFnpva72CsfY2aI3CSTuoTq0LHVh+mrNTW2aRo0WY3ThGTCzolHBxemvLTWeCar/skFBpz4cOgdZP1VmgdhdWzEhxcePAmlpRWTY3605HOWWK6ZBPhIP5rmIMoMpZdPQi0jzFdr7ieVTVcbIxXKpbnYyn9mUsGsPV+QdGqztiKN/nzFlLpUux2Awnbvi5J9sdcz6JBn9fvGeuyIGGlZ7TozV0t4ZFggdv0UFbfAHYElXcKCQiLiSo8npDkrAr1Khz3dSoAPDKiEpVjY0NFOOogTkZwwXd/N9b2TL3zy4P/9rHy/NtnP1F146hWAahO7d+eZqpRU9IFcPfrwvSia5AvkqgORPreLx3/Eyyv0swFBPZ/lV/suyM20iADXaSxOWdKaeOuhbxsD3WE1MYbQVBnxV7JJdq2AQg9yo658h07na+7bv3OO2nzhIbV84U/7k5Du0WVniaj8qyZPg4NUiJh/h1DXFNrBldA=
    admin-user: AgBZQxgIZXHLvKmcijzStwMNxUlGu6v6uQICB2jskfWcUHbkIiK26cJjaafxUxrfXh0kl3VlFAm3PkHbiVkFyOnVtPeEI+GSnZM+sApojFH1expsUJheZmT3lg2yaMV26RgetsoT8SFtnUOzIt/i7G4pTZdxp8TpVTNDwFYj1kLybTGOOT5ltEZyLhJ7inTzq3KRLHk7kAX31arwhdIapzLdw8dMEnmwtr7ZRaHehBDKhMy7IrC+smuqA0o4EURGa2OPNStM6ME3QOFEWqvVZN24wI6eEW4AqZNsVmGv3nNA9oxsbssq8B20TJ/v7BnN6W/7FZC4G8xDITOapTuKEI1FrBhEPpNecxvKYM38kdTc4mUXoaim+/8NKQ9pJZrmlQfI/dpG7C4DhmbW2ej5hHE0e453rUisfuCKwBV54R9liGjW3atJW3Q0+Tx8/9jPcq1rpyNKGPAJPslyWHuJhjIJgEwTwJmvrVnf+bJqlvl0d9OhTx8l/9yZrcIZomRCgHiW+0m3ih46JSAYrFqKBUe7jSJLdUq8qo0vFhI3pwaaYXdQ7+mUDQHFMvohTZh8B3kgOd9Qkv92twicqQ0pL6EYGyED136kQrE26EM80bemlA7qyfQ/spWxtUe6wGw9RoxjLL/FX3ykk3acj3oeX4sydvQG0Dr19bSTfQpI+/GqeNXIIilSRsiANb1StI2H13qehT25Vg==
  template:
    metadata:
      creationTimestamp: null
      name: zenyard-grafana
      namespace: zenyard
