---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zenyard-db
  namespace: zenyard
spec:
  encryptedData:
    DB_PASSWORD: AgA93gTYQeCNBbef7Kw4vOHDVVnJuTcaQeKnvDhWm77gZ+L4h2J+ly+cpB9HMxhlofcOpazKYLTdZV2ZGMHP/brI2HEul4jabT36vnu2RE/hmYyJ7GiS6UWf9RA30MLrP84Rf4W9O8TH2Pd0+Db1LvhveQu2Z5YCakIiUcC7SJMh3I/dYXLAegatID4Ovkc1GoG/pMSSK4NGZtPRRrpzewBkGScbNLIR9WOeyM/d5w8g5qLCvojwLi7r1xXrDqtp8bw8VeEHztZ6KYw/64WE0X45kmKLuKivYbaPuVtUBV9VfqDN0cIYiIbTAdn+5yIcUMVyWAxHhdm64OcZeAzEyHvuw0nYHqwX59Xw4vwCUGGcyb/XuWIaX7h4XdQGlI/jduQ3UgC9z79GyQuC9KjorGjhMVS3JG5xHD6ddKycIWtW2cZhyN69aEgGsj/kS0uDwCX3/Pi9uVQ2QD23eR7agHRFHjyA0RkohnRBHkfpk6Hn/EUql4UNL95Jh3gMZ0g3lrmzeItTEP0Fo4yNlEZUV8oaBWQZ4wp5M90rZMDyX3Kw0DF0OQbJdp/XECtd//Fwoj8Jn9cFvizjrgwtzP+79B6yJI+E3+pwSM5DIiAgsd1R0mCKWP33V6fWSuhZChSt3o+I1bhQYVd9vENMX+hxF1nKQ4JX43+pSs4ztEuah7He1otYka9WM2eJsaXEOZfYwxLL+iu0ogxEBIr6EcCpv/wogWrU8FyG+dY=
    DB_USER: AgChnhE6hE25/yX4VkBkVlRhcWXHZNXE2ISD9pf+fjVDurfyw1cyxyDoMIcQwTSoF1fq4JDnc4aNKlO+BuaXTBqlbpYK3X+/+QYf9Nns9MZJsW+0LTcAQXOagoL3IQewoD2mbxA47XD2u9UW9Ww0JwuaHpS6BUHvhs2EAoRFSIZFmpYL01aCCKKKh6J/4o5/ZdW5etR5cHO3EMGvd4qh+xW5XyGnSZ3FxldABmMBJa0rg8PcF8aEGN9xUjhShrZfrGHjB5+RpIORCUxU7Zl0qQn35/jJg0ZZuVnO1OeNoeWyA/LcxzwsYywLwy3v11OgLtKD7v+p7MDBkyz7ZFo+NUJEevKiyjeLR0xGNs/rhBLj91sp7KjS/SyatFQuqslFFIukbmMY/MJJ7V3WwExKPaCgXYUXZYoRED//xCMP5LyhQ37e3QYoUMgxfVaqHE4MIik/hiiW7AnTAQ96YX/YlumSsnmuaEctB6hBpG/VlYJV6bUb4a7OaETbUoN4m3x9aPdelOCN+qj5/HjShJFzvZmnKxy2IltH3oEbOF/7HHi+GITf2KAy7N/Ap27XtX2cmUuoDco+7KlyyYTY+3xMNmMIpcLMzJAegj4YAf5kVO58PlYZoRIMl/dzbGHxhJxF8cHG5AdTTn6lyF53HyTJ6xxwi1LhcZLnBZ1P5N1KeR4v1FmUQEf1arv8CL6SROMfqVsQpCKlLbwS
  template:
    metadata:
      creationTimestamp: null
      name: zenyard-db
      namespace: zenyard
