apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zenyard.fullname" . }}-api
  labels:
    {{- include "zenyard.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zenyard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "zenyard.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: {{ include "zenyard.fullname" . }}-app
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "zenyard.dbSecretName" . }}
                  key: {{ .Values.database.secretKeys.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "zenyard.dbSecretName" . }}
                  key: {{ .Values.database.secretKeys.password }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
