apiVersion: v1
kind: Service
metadata:
  name: {{ include "zenyard.fullname" . }}-api
  labels:
    {{- include "zenyard.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "zenyard.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
