{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenyard.dbSecretName" . }}
  labels:
    {{- include "zenyard.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  DB_USER: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
{{- end }}
