apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zenyard.fullname" . }}-app
  labels:
    {{- include "zenyard.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
